# Generated by Django 4.0 on 2022-03-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
