# Generated by Django 4.0 on 2022-03-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_favoritefilms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritefilms',
            options={'verbose_name': 'Favorite Films', 'verbose_name_plural': 'Favorite Films'},
        ),
    ]
