# Generated by Django 4.0 on 2022-03-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_favoritefilms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFavoriteMovie',
            field=models.BooleanField(default=False),
        ),
    ]
