# Generated by Django 4.0 on 2022-03-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingmovie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmovie',
            name='created_rating_time',
        ),
    ]
