# Generated by Django 4.0 on 2022-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingmovie', '0002_remove_ratingmovie_created_rating_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmovie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
