# Generated by Django 4.0 on 2022-03-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=50)),
                ('description_post', models.TextField()),
                ('image_post', models.ImageField(upload_to='postimages')),
                ('update_data_post', models.DateTimeField(auto_now=True)),
                ('created_date_post', models.DateTimeField(auto_now_add=True)),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorpost', to='profiles.profile')),
                ('liked_post', models.ManyToManyField(blank=True, default=None, related_name='likedpost', to='profiles.Profile')),
            ],
        ),
    ]
