# Generated by Django 4.0 on 2022-01-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_actor', models.CharField(max_length=50)),
                ('last_name_actor', models.CharField(max_length=50)),
                ('biography_actor', models.TextField(max_length=3000)),
                ('image_actor', models.ImageField(upload_to='actorimages')),
                ('date_of_birth_actor', models.DateField()),
                ('gender_actor', models.CharField(choices=[('M', 'Men'), ('F', 'Woman')], max_length=50)),
                ('duty_type_actor', models.CharField(choices=[('1', 'Director'), ('2', 'Writer'), ('3', 'Actorisa')], max_length=50)),
                ('height_actor', models.FloatField()),
                ('country_actor', models.CharField(max_length=30)),
                ('slug_actor', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_tag_name', models.CharField(max_length=30)),
                ('actor_slug_tag', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmCategoryMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slugcategory', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slugtag', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_movie', models.CharField(max_length=50)),
                ('description_movie', models.TextField(max_length=3000)),
                ('image_movie', models.ImageField(upload_to='movieimages')),
                ('date_created_movie', models.DateField()),
                ('slug_movie', models.SlugField(unique=True)),
                ('budget_movie', models.DecimalField(decimal_places=2, max_digits=20)),
                ('language_movie', models.CharField(max_length=30)),
                ('slider_movie', models.BooleanField(default=False)),
                ('avarage_ibdm', models.FloatField(default=0)),
                ('video_movie', models.FileField(upload_to='movieivideos')),
                ('video_time', models.CharField(max_length=30)),
                ('theater_movie', models.BooleanField(default=False)),
                ('ontv_movie', models.BooleanField(default=False)),
                ('actor_movie', models.ManyToManyField(to='movie.Actor')),
                ('category_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.filmcategorymovie')),
                ('tag_movie', models.ManyToManyField(to='movie.TagMovie')),
            ],
        ),
    ]
