# Generated by Django 4.0 on 2022-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth_actor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created_movie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
