# Generated by Django 4.0 on 2022-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_actor_date_of_birth_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actortag',
            name='actor_slug_tag',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filmcategorymovie',
            name='slugcategory',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tagmovie',
            name='slugtag',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
