# Generated by Django 4.0 on 2022-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_actortag_actor_slug_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actortag',
            name='actor_slug_tag',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmcategorymovie',
            name='slugcategory',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tagmovie',
            name='slugtag',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
