# Generated by Django 4.0 on 2022-01-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_actortag_actor_slug_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category_movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='category_movie',
            field=models.ManyToManyField(null=True, to='movie.FilmCategoryMovie'),
        ),
    ]
