# Generated by Django 4.0 on 2022-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_movie_category_movie_movie_category_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mmpa_rating_movie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category_movie',
            field=models.ManyToManyField(to='movie.FilmCategoryMovie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug_movie',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
