# Generated by Django 4.0 on 2022-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_mmpa_rating_movie_alter_movie_category_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug_actor',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
