# Generated by Django 4.0 on 2022-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_actor_slug_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_actor',
            field=models.ImageField(blank=True, null=True, upload_to='actorimages'),
        ),
    ]
