# Generated by Django 4.0 on 2022-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_actor_image_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='duty_type_actor',
            field=models.CharField(choices=[('1', 'Director'), ('2', 'Writer'), ('3', 'Actorisa'), ('4', 'Producter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category_movie',
            field=models.ManyToManyField(related_name='category_movie', to='movie.FilmCategoryMovie'),
        ),
    ]
