# Generated by Django 4.0 on 2022-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_actor_duty_type_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_imbd',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
