# Generated by Django 4.0 on 2022-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_actor_actor_imbd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='duty_type_actor',
            field=models.CharField(choices=[('Director', 'Director'), ('Writer', 'Writer'), ('Actorisa', 'Actorisa'), ('Producter', 'Producter')], max_length=50),
        ),
    ]
