# Generated by Django 4.0 on 2022-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_actor_duty_type_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedMovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_relatedmovie', models.CharField(max_length=100)),
                ('slug_relatedmovie', models.SlugField(unique=True)),
                ('created_relatedmovie', models.CharField(max_length=100)),
                ('imdb_relatedmovie', models.CharField(max_length=20)),
                ('overview_relatedmovie', models.TextField()),
                ('image_relatedmovie', models.ImageField(upload_to='movierelated')),
            ],
        ),
    ]
