# Generated by Django 4.0 on 2022-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_relatedmoviemodel_idvalue_relatedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmoviemodel',
            name='image_relatedmovie',
            field=models.CharField(max_length=100),
        ),
    ]
