# Generated by Django 4.0 on 2022-02-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_relatedmoviemodel_slug_relatedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmoviemodel',
            name='idvalue_relatedmovie',
            field=models.CharField(max_length=100),
        ),
    ]
