# Generated by Django 4.0 on 2022-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_alter_relatedmoviemodel_idvalue_relatedmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedmoviemodel',
            name='slug_relatedmovie',
        ),
    ]
