# Generated by Django 4.0 on 2022-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_remove_relatedmoviemodel_slug_relatedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isFavoriteMovie',
            field=models.BooleanField(default=False),
        ),
    ]
