# Generated by Django 4.0 on 2022-03-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_movie_isfavoritemovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='isFavoriteMovie',
        ),
    ]
