# Generated by Django 4.0 on 2022-04-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=100)),
                ('slug_category', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tag', models.CharField(max_length=100)),
                ('slug_tag', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=50)),
                ('description_post', models.TextField()),
                ('image_post', models.ImageField(upload_to='postimages')),
                ('slug_post', models.SlugField(blank=True, unique=True)),
                ('update_data_post', models.DateTimeField(auto_now=True)),
                ('created_date_post', models.DateTimeField(auto_now_add=True)),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorpost', to='profiles.profile')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorypost', to='postblog.category')),
                ('tag_post', models.ManyToManyField(blank=True, related_name='tagmovie', to='postblog.Tag')),
            ],
        ),
    ]
