# Generated by Django 4.0 on 2022-04-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0002_likepostfilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_post', models.ImageField(upload_to='imagepostfk')),
                ('postfilm_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postblog.postfilm')),
            ],
        ),
    ]
