# Generated by Django 4.0 on 2022-04-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0005_alter_postfilm_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfilm',
            name='image_post',
        ),
    ]
