# Generated by Django 4.0 on 2022-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0006_remove_postfilm_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_post',
            field=models.ImageField(default='images/sekiltapilmadi.jpg', upload_to='imagepostfk'),
        ),
    ]
