# Generated by Django 4.0 on 2022-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0009_alter_imagepost_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilm',
            name='slug_post',
            field=models.SlugField(blank=True),
        ),
    ]
