# Generated by Django 4.0 on 2022-04-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='postfilm_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagepostfilmfk', to='postblog.postfilm'),
        ),
    ]
