# Generated by Django 4.0 on 2022-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0012_alter_imagepost_postfilm_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_post',
            field=models.ImageField(default='sekiltapilmadi.jpg', upload_to='imagepostfk'),
        ),
    ]
