# Generated by Django 4.0 on 2022-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postblog', '0013_alter_imagepost_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_post',
            field=models.ImageField(default='notfoundimages.jpg', upload_to='imagepostfk'),
        ),
    ]
